### ISSUE TITLE
Updating of JRubyJar dependencies needs to happen at a different point in the Gradle lifecycle

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-plugin#183]
For the [storm plugin](/jruby-gradle/jruby-gradle-storm-plugin) I'm moving code around to make use of the `JRubyJar` task. To do so I've created a `JRubyStormJar` task which subclasses `JRubyJar`

This task is then created in the constructor of a third task, e.g.

```groovy
JRubyStorm() {
  this.assembleTask = project.task('someName', type: JRubyStormJar)
}
```

When the project is evaluated that uses this `jrubyStorm` task, the following will occur:

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'test'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:495)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:89)
	at com.github.jrubygradle.storm.JRubyStormTaskIntegrationSpec.evaluation of the project should result in an assemble and run task(JRubyStormTaskIntegrationSpec.groovy:39)
Caused by: org.gradle.api.InvalidUserDataException: Cannot change dependencies of configuration ':jrubyJar' after it has been resolved.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:578)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.run(DefaultConfiguration.java:137)
	at org.gradle.api.internal.DefaultDomainObjectCollection.assertMutable(DefaultDomainObjectCollection.java:267)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:158)
	at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:81)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.doAdd(DefaultDependencyHandler.java:84)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.add(DefaultDependencyHandler.java:61)
	at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.add(DefaultDependencyHandler.java:57)
	at com.github.jrubygradle.jar.JRubyJar.addJRubyDependencies(JRubyJar.groovy:203)
	at com.github.jrubygradle.jar.JRubyJar$_closure1.doCall(JRubyJar.groovy:195)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 4 more
```

The use of `project.afterEvaluate()` for adding dependencies to configurations for the `JRubyJar` task I think is sufficiently unreliable to where we should find alternative means.

**Comment by rtyler** [comment]
One idea I'm noodling about is overwriting `configure` and making it add JRuby dependencies in an idempotent fashion. This would require removing existing dependencies if present in the `configuration` and adding the appropriate ones for how the task is configured

**Comment by ysb33r** [comment]
There is special support for default dependencies in Gradle 2.5. We might have to look at using that at some point in the future.

**Comment by rtyler** [comment]
I've reproduced this bug with a simple test-case and it has nothing to do with the storm plugin "fortunately" 

```gradle
apply plugin: 'com.github.jruby-gradle.jar'

import com.github.jrubygradle.jar.JRubyJar
task someJar(type: JRubyJar) {
}
```

Executing the `someJar` task results in


```
    Error:

    FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred configuring root project 'junit416338864208339164'.
    > Cannot change dependencies of configuration ':jrubyJar' after it has been resolved.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    -----
    Reason:
    Cannot change dependencies of configuration ':jrubyJar' after it has been resolved.
    -----
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:94)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:91)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:161)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:91)
        at com.github.jrubygradle.jar.JRubyJarIntegrationSpec.executing the assemble task produces a jar artifact(JRubyJarIntegrationSpec.groovy:46)
```

**Comment by rtyler** [comment]
I've come to the conclusion that this can be solved relatively easily by making sure that the addition of jruby dependencies happens on instantiation, or when configuration, jrubyMainsVersion or jrubyVersion gets modified. HOWEVER, that will result in this code failing to use the right JRuby version:

```gradle
jruby.defaultVersion = '1.7.11'
jrubyJar { initScript 'main.rb' }
```

I fear this is a chicken and an egg situation and the only way to correct it is to have `base` call some callbacks whenever `defaultVersion` or `execVersion` are executed.

I'm going to step away from the computer and ponder this some more before I set out in that direction
