### ISSUE TITLE
Can't resolve latest version of a dependency (e.g 'rubygems:colorize:+')

### ISSUE THREAD

**Issue by michaelwoodson** [jruby-gradle/jruby-gradle-plugin#267]
Ran into this problem trying to upgrade to version 1.2.0 of jruby-gradle-plugin in another project that depends on it; that project uses a dependency in this format: 'rubygems:compass:+'.  With jruby 1.2.0 I get an exception from gradle trying to resolve dependencies.  I was able to reproduce the exception with this build.gradle:

``` gradle

import com.github.jrubygradle.JRubyExec

buildscript {
   repositories { jcenter() }

  dependencies {
    classpath "com.github.jruby-gradle:jruby-gradle-plugin:1.2.0"
  }
}

apply plugin: "com.github.jruby-gradle.base"

dependencies {
  jrubyExec "rubygems:colorize:+"
}

task printSomePrettyOutputPlease(type: JRubyExec) {
  description "Execute our nice local print-script.rb"
  script "${projectDir}/print-script.rb"
}
```
Attempting to run the printSomePrettyOutputPlease task will give this exception resolving dependencies:
```
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '' with class 'java.lang.String' to class 'int'
	at com.github.jrubygradle.internal.GemVersion.compare(GemVersion.groovy:182)
	at com.github.jrubygradle.internal.GemVersion.conflict(GemVersion.groovy:202)
	at com.github.jrubygradle.internal.GemVersion$conflict$0.call(Unknown Source)
	at com.github.jrubygradle.internal.GemVersionResolver.resolve(GemVersionResolver.groovy:74)
	at com.github.jrubygradle.internal.GemVersionResolver$_closure1_closure4.doCall(GemVersionResolver.groovy:28)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:193)
	at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:183)
	at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:76)
	at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:76)
	at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DependencySubstitutionResolver.resolve(DependencySubstitutionResolver.java:40)
	... 110 more
```
It looks like there is a straightforward fix in GemVersion.groovy (it is trying to cast to an int variable after testing to see that the string is not an int).  Not sure if this case should be caught upstream though.

**Comment by mkristian** [comment]
I think the ```Gem::Version``` does not handle the case ```rubygems:compass:+``` - so any PR fixing this is most welcome ;)

**Comment by michaelwoodson** [comment]
Yeah, I couldn't find any documentation to support that construction, but it seems to have worked in the past.  I did some more experimentation and found that `rubygems:compass:[0.0,)` is a workaround.  I'll look at making a PR just to keep from throwing an exception in this case.
