### ISSUE TITLE
Cannot cast object extension jruby

### ISSUE THREAD

**Issue by yooksi** [jruby-gradle/jruby-gradle-plugin#421]
Gradle version: `6.8.2`
Plugin version: `jruby-gradle.base:2.0.1`

```
* What went wrong:
Could not determine the dependencies of task ':generateChangelog'.
> Cannot cast object 'extension 'jruby'' with class 'com.github.jrubygradle.JRubyPluginExtension_Decorated' to class 'org.ysb33r.grolifant.api.AbstractCombinedProjectTaskExtension'

Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'extension 'jruby'' with class 'com.github.jrubygradle.JRubyPluginExtension_Decorated' to class 'org.ysb33r.grolifant.api.AbstractCombinedProjectTaskExtension'
	at org.ysb33r.grolifant.api.AbstractCombinedProjectTaskExtension.getProjectExtension(AbstractCombinedProjectTaskExtension.groovy:101)
	at com.github.jrubygradle.JRubyPluginExtension_Decorated.getProjectExtension(Unknown Source)
	at com.github.jrubygradle.JRubyPluginExtension.getExtFromProject(JRubyPluginExtension.groovy:305)
	at com.github.jrubygradle.JRubyPluginExtension.getGemPrepareTaskName(JRubyPluginExtension.groovy:282)
	at com.github.jrubygradle.JRubyPluginExtension_Decorated.getGemPrepareTaskName(Unknown Source)
	at com.github.jrubygradle.JRubyExec$_closure3.doCall(JRubyExec.groovy:83)
```

**Comment by ysb33r** [comment]
Looks like you have a mix up of a newer version of Grolifant being introduced by another plugin. DO you have an example of your build script?

**Comment by yooksi** [comment]
Unfortunately I've moved on to different solutions and no longer have access to code that caused this.
