### ISSUE TITLE
Gradle 7 deprecation warnings

### ISSUE THREAD

**Issue by boris-petrov** [jruby-gradle/jruby-gradle-plugin#435]
Using the `com.github.jrubygradle.JRubyExec` task type leads to (on Gradle 7.6):

```
Invocation of Task.project at execution time has been deprecated. This will fail with an error in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.6/userguide/upgrading_version_7.html#task_project
        at org.gradle.configurationcache.DeprecatedFeaturesListenerManagerAction$DeprecatedFeaturesListener.onProjectAccess(DeprecatedFeaturesListenerManagerAction.kt:70)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:462)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:444)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:69)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:433)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:221)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:192)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy145.onProjectAccess(Unknown Source)
        at org.gradle.api.internal.AbstractTask.notifyProjectAccess(AbstractTask.java:1068)
        at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:235)
        at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
        at com.github.jrubygradle.JRubyExec.getGemWorkDir(JRubyExec.groovy:186)
        at com.github.jrubygradle.JRubyExec_Decorated.getGemWorkDir(Unknown Source)
        at com.github.jrubygradle.JRubyExec.exec(JRubyExec.groovy:261)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
```

**Comment by UweKubosch** [comment]
I will be looking at this soon.  PR is welcome!  😄
